#ifndef TOKENS_H
#define TOKENS_H

#define L_EOF                       -1

// Decimals
#define DEC_DIGIT_NO_ZERO          300
#define DEC_DIGIT                  301
#define DEC_DIGIT_OR_SEPARATOR     302
#define DEC_DIGITS                 303
#define DOUBLE_EXPONENT            304

// Reals
#define REAL_LITERAL              305
#define FLOAT_LITERAL             306
#define DOUBLE_LITERAL            307
#define INTEGER_LITERAL           308
#define HEX_DIGIT                 309
#define HEX_DIGIT_OR_SEPARATOR    310
#define HEX_LITERAL               311
#define BIN_DIGIT                 312
#define BIN_DIGIT_OR_SEPARATOR    313
#define BIN_LITERAL               314
#define UNSIGNED_LITERAL          315
#define LONG_LITERAL              316
#define BOOLEAN_LITERAL           317
#define NULL_LITERAL              318
#define CHARACTER_LITERAL         319
#define UNI_CHARACTER_LITERAL     320
#define IDENTIFIER                321
#define LIT_STRING                322
#define LC_BRACKET                323
#define RC_BRACKET                324
#define LS_BRACKET                325
#define RS_BRACKET                326
#define LA_BRACKET                327
#define RA_BRACKET                328
#define LC_PARENTHESIS            329
#define RC_PARENTHESIS            330
#define EXCLAMATION               331
#define THREE_DOTS                332
#define HASH                      333
#define AT                        334
#define QUESTION                  335
#define COLON                     336
#define SEMICOLON                 337
#define DOUBLE_SEMICOLON          338

// Keywords
#define RETURN_AT                 400
#define CONTINUE_AT               401
#define BREAK_AT                  402
#define THIS_AT                   403
#define SUPER_AT                  404
#define KT_FILE                   405
#define FIELD                     406
#define PROPERTY                  407
#define GET                       408
#define SET                       409
#define RECEIVER                  410
#define PARAM                     411
#define SETPARAM                  412
#define DELEGATE                  413
#define PACKAGE                   414
#define IMPORT                    415
#define CLASS                     416
#define INTERFACE                 417
#define FUN                       418
#define OBJECT                    419
#define VAL                       420
#define VAR                       421
#define TYPE_ALIAS                422
#define CONSTRUCTOR               423
#define BY                        424
#define COMPANION                 425
#define INIT                      426
#define THIS                      427
#define SUPER                     428
#define TYPEOF                    429
#define WHERE                     430
#define IF                        431
#define ELSE                      432
#define WHEN                      433
#define TRY                       434
#define CATCH                     435
#define FINALLY                   436
#define FOR                       437
#define DO                        438
#define WHILE                     439
#define THROW                     440
#define RETURN                    441
#define CONTINUE                  442
#define BREAK                     443
#define AS                        444
#define IS                        445
#define IN                        446
#define NOT_IS                    447
#define NOT_IN                    448
#define OUT                       449
#define DYNAMIC                   450
#define PUBLIC                    451
#define PRIVATE                   452
#define PROTECTED                 453
#define INTERNAL                  454
#define ENUM                      455
#define SEALED                    456
#define ANNOTATION                457
#define DATA                      458
#define INNER                     459
#define VALUE                     460
#define TAILREC                   461
#define OPERATOR                  462
#define INLINE                    463
#define INFIX                     464
#define EXTERNAL                  465
#define SUSPEND                   466
#define OVERRIDE                  467
#define ABSTRACT                  468
#define FINAL                     469
#define OPEN                      470
#define CONST                     471
#define LATEINIT                  472
#define VARARG                    473
#define NOINLINE                  474
#define CROSSINLINE               475
#define REIFIED                   476
#define EXPECT                    477
#define ACTUAL                    478

// Operators
#define SUBTRACTION              500
#define MULTIPLICATION           501
#define DIVISION                 502
#define MODULUS                  503
#define INCREMENT                504
#define DECREMENT                505
#define AUGM_ASSIGN_ADD          506
#define AUGM_ASSIGN_SUB          507
#define AUGM_ASSIGN_MULT         508
#define AUGM_ASSIGN_DIV          509
#define AUGM_ASSIGN_MOD          510
#define EQUAL_TO                 511
#define NOT_EQUAL_TO             512
#define GREATER_THAN             513
#define LESS_THAN                514
#define GREATER_THAN_EQUAL       515
#define LESS_THAN_EQUAL          516
#define LOGICAL_AND              517
#define LOGICAL_OR               518
#define LOGICAL_NOT              519
#define REF_EQUAL                520
#define REF_NOT_EQUAL            521
#define ACCESS_LEFT              522
#define ACCESS_RIGHT             523
#define ASSERT_NON_NULLABLE      524
#define SAFE_CALL                525
#define ELVIS                    526
#define CREATE_REF               527
#define CREATE_RANGE             528
#define CREATE_RANGE_LESS        529
#define SEPERATE_NAME            530
#define NULLABLE                 531
#define SEPARATES_LAMBDA         532
#define ANNOTAION                533
#define SEPARATES_STATEMENT      534
#define REF_AS_STRING            535
#define SUBSTITUTE_UNUSED_LAMBDA 536
#define COMMA                    537
#define DOT                      538

// Comments and Whitespace
#define LF                       600
#define CR                       601
#define NL                       602
#define WS                       603
#define SHEBANG_LINE            604
#define DELIMITED_COMMENT        605
#define COMMENT                  606

#endif